language: node_js
node_js:
    - lts/*
cache: yarn
install:
    - yarn install
script:
    - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $ACCESS_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
      branch: docs

    
    
#  repo: Repo slug, defaults to current repo. Note: The slug consists of username and repo name and is formatted like user/repo-name.
#  target_branch: Branch to (force, see: keep_history) push local_dir contents to, defaults to gh-pages.
#  keep_history: Optional, create incremental commit instead of doing push force, defaults to false.
#  fqdn: Optional, sets a custom domain for your website, defaults to no custom domain support.
#  project_name: Defaults to value of fqdn or repo slug, used for metadata.
#  email: Optional, committer info, defaults to deploy@travis-ci.org.
#  name: Optional, committer, defaults to Deployment Bot.
#  committer_from_gh: Optional, defaults to false. Allows you to use the token’s owner name and email for commit. Overrides email and name options.
#  allow_empty_commit: Optional, defaults to false. Enabled if only keep_history is true.
#  github_url: Optional, the URL of the self-hosted GitHub enterprise, defaults to github.com.
#  verbose: Optional, be verbose about internal steps, defaults to false.
#  deployment_file: Optional, defaults to false, enables creation of deployment-info files.
