name: ssccs-docs

on:
 #push:
 #  branches:
 #    - docs
 #  paths-ignore:
 #    - '**/__tests__/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '14'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install pnpm
        run: npm install -g pnpm@next-7


      - name: Install dependencies
        run: pnpm install

      - name: Build documentation site
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          repo: seasideccm/seasideccm.github.io
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
