name: ssccs-docs

on:
 #push:
 #  branches:
 #    - docs
 #  paths-ignore:
 #    - '**/__tests__/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '16'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Docs build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          repo: seasideccm/seasideccm.github.io
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
